config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :new
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  patch 'tasks/:id', to: 'tasks#update'
  post 'tasks', to: 'tasks#create', as: :create
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @tasks = Task.find(params[:id])
    @tasks.update(task_params)
    redirect_to task_path(@tasks)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container form-inline">
  <%= form_for(@task) do |f| %>
    <div class="form-group form-inline">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group form-inline">
      <%= f.label :details %>
      <%= f.text_field :details, class: 'form-control' %>
    </div>

    <div class="form-group form-inline">
      <%= f.label :completed %>
      <%= f.check_box :completed, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My Tasks</h1>
  <ul class="">
    <% @tasks.each do |task| %>
      <% if task.completed %>
        <li>
          <%= link_to task_path(task) do %>
            <i class="far fa-check-square"></i> <%= task.title %>
          <% end %>
          <%= link_to task_path(task) do %>
            <i class="far fa-check-square"></i>
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to task_path(task) do %>
            <i class="far fa-square"></i> <%= task.title %>
          <% end %>
          <%= link_to task_path(task),
          method: :delete,
          data: { confirm: "Are you sure?" } do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
  <%= link_to new_path do %>
    <i class="fas fa-plus"></i> Add a new task
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="container form-inline">
  <%= form_for(@task) do |task| %>
    <div class="form-group form-inline">
      <%= task.label :title %>
      <%= task.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group form-inline">
      <%= task.label :details %>
      <%= task.text_field :details, class: 'form-control' %>
    </div>

    <div class="form-group form-inline">
      <%= task.label :completed %>
      <%= task.check_box :completed, class: 'form-control' %>
    </div>

    <%= task.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row block-inline">
    <h1> <%= @task.title %> <%= link_to 'EDIT', edit_task_path, {:class=>"btn btn-warning"}  %> </h1>
  </div>
  <p><%= @task.details %></p>
  <% if @task.completed %>
    <p><i class="far fa-check-square"></i> This task is completed</p>
  <% else %>
    <p><i class="far fa-square"></i> This task is not completed yet</p>
  <% end %>
  <%= link_to tasks_path do %>
    <i class="fas fa-reply"></i> Back to list
  <% end %>
</div>